Добавил GitHub Action
surfstudio/flutter-analytics pull request #1
Opened 2021-09-28 12:04 UTC by VVPAK

2021-09-28 12:25 UTC, dkrutskikh requested changes

2021-09-28 12:25 UTC, dkrutskikh commented on .github/workflow/build.yaml
> +      - name: Install lcov 🔧
@VVPAK lcov нужен что-бы считать покрытие тестами, сейчас это не нужно

2021-09-28 12:31 UTC, VVPAK commented on .github/workflow/build.yaml
> +      - name: Install lcov 🔧
Готово

2021-09-28 15:47 UTC, dkrutskikh submitted a review, later dismissed

2021-09-29 07:00 UTC, VVPAK commented
Обновил конфиг.
Добавил покрытие тестами, проверку readme.

2021-09-30 07:22 UTC, closed without merging